### ISSUE TITLE
subjectID for OhJ_2014

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#10]
The subjectID for OhJ_2014 should be capitalized to be consistent with the other datasets, such as "hv07" -> "HV07"

**Comment by lwaldron** [comment]
Does this mean changing changing the subject identifiers used by the original studies? In general I favor leaving those as-is, unless there is a compelling reason to change them. What is the reason for standardizing subject identifiers?

**Comment by edoardopasolli** [comment]
subjectID fields in OhJ_2014 have been fixed
