### ISSUE TITLE
country

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#12]
it is missing what values correspond to. For example we should indicate that CAN=CANADA, DNK=Denmark, etc.

**Comment by lwaldron** [comment]
The description column in `inst/extdata/template.csv` says:

> Country of acquisition using ISO3 code from http://www.fao.org/countryprofiles/iso3list/en/

Is the issue more that these descriptions do not make it to `pData` or `combined_metadata`?

**Comment by edoardopasolli** [comment]
Yes! I was referring to the country field, but the same is true for the other ones

**Comment by lwaldron** [comment]
@schifferl would you add these descriptions to the metadata of the ExpressionSets and the combined_metadata? For the esets, it's varMetadata(); for example:

```
> example("ExpressionSet")
> varMetadata(expressionSet)
      labelDescription
sex        Female/Male
type      Case/Control
score    Testing Score
```

If combined_metadata were a `DataFrame`, it would be in `metadata(combined_metadata)`, but I don't know what the options are for a `tbl_df`. I would probably suggest going the "Bioconductor way" and using a `DataFrame` which has metadata in a place many users will expect.

Metadata should be mentioned in the man pages and vignette.

**Comment by schifferl** [comment]
Ok, I will convert the `combined_metadata` to a `DataFrame` and add the descriptions. I agree too, the metadata should be mentioned in the `?curatedMetagenomicData` man page and perhaps even have it's own man page.

**Comment by lwaldron** [comment]
I'd say `?curatedMetagenomicData` could just explain what is provided by the important accessors of the `ExpressionSet` objects (`exprs`, `pData`, `varMetadata`, `rownames`, `colnames`), and also mention the other key components of the package: conversion to `phyloseq` and `metagenomeSeq`, and the `combined_metadata` table, with these listed under See Also). Then the metadata can be documented under `?combined_metadata` and in the vignette.

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataPipeline#2
