### ISSUE TITLE
Addition of Loomba et al. dataset

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#13]
_From @fplaza on December 8, 2017 14:41_

Could you add this dataset http://dx.doi.org/10.1016/j.cmet.2017.04.001 to curatedMetagenomicData?
The SRA files are available here: https://www.ncbi.nlm.nih.gov/bioproject/373901
Thanks

_Copied from original issue: waldronlab/curatedMetagenomicData#119_

**Comment by schifferl** [comment]
_From @edoardopasolli on December 8, 2017 15:36_

Great dataset, thanks for the suggestion!

**Comment by edoardopasolli** [comment]
The dataset has been included in cMD. I can close this issue.
