### ISSUE TITLE
File of duplicate samples

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#14]
_From @lwaldron on December 8, 2017 21:49_

@paolinomanghi would you create a spreadsheet of duplicates, perhaps like this?
`study1   sampleID1   study2    sampleID2`

The assignment of "1" and "2" would be significant in that, when the user selects an option like `removeduplicates=TRUE`, the samples in study 2 would by default be the ones removed. I would relegate the smaller study to study 2, unless there is a better reason to think of one of the studies as the preferable default (like better metadata or data quality). 

If a sample is duplicated in three studies, all three edges in that graph would have to be shown, meaning there would be three rows to identify the duplication of a single sample.

This spreadsheet can then be made into a documented dataframe in the data/ directory (`DataFrame` would be the Bioconductor way, although we've already gone rogue with a `tbl_df` combined_metadata).

_Copied from original issue: waldronlab/curatedMetagenomicData#120_

**Comment by schifferl** [comment]
_From @paolinomanghi on December 9, 2017 12:30_

Yes, I'm collecting all the necessities and organising them. Want to avoid
any confusion in the future, and any difficulty in handling the whole
dataset.

**Comment by lwaldron** [comment]
A note from issue #8, which I will close as a duplicate:

> It seems that the "LiJ_2014" overlaps in some way with three other datasets: "LeChatelierE_2013", "NielsenHB_2014", "QinJ_2012".

**Comment by paolinomanghi** [comment]
Yes, it's just that I need to correct the metadata before compiling a good
duplicate table, or at least this was the idea.

**Comment by lwaldron** [comment]
@paolinomanghi it would be great to include a table of known duplicates in the Bioconductor 3.15 release.

**Comment by AndreaZen-1** [comment]
I made the table as described in the first comment on this Issue.
I uploaded it in curatedMetagenomicDataCuration/inst/extdata/duplicates_table.tsv

Let me know if anything else is needed, for now I'm closing.
