### ISSUE TITLE
NCBI_accession corresponds to sample_id in place of run_id for HMP samples

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#16]
_From @fplaza on December 6, 2017 14:51_

Hello,

In the file _combined_metadata.rda_, the field NCBI_accession corresponds to the sample_id in place of the run_id for HMP samples.

For example:
dataset_name | sampleID | subjectID | NCBI_accession
HMP_2012 | SRS056519 | HMP_2012_765094712 | SRS056519
HMP_2012 | SRS018427 | HMP_2012_160218816 | SRS018427

Should be replaced by:
dataset_name | sampleID | subjectID | NCBI_accession
HMP_2012 | SRS056519 | HMP_2012_765094712 | SRR063503;SRR063504
HMP_2012 | SRS018427 | HMP_2012_160218816 | SRR059916;SRR059917

Thank you.

_Copied from original issue: waldronlab/curatedMetagenomicData#115_

**Comment by schifferl** [comment]
Thank you @fplaza. This applies to all of the HMP metadata?

**Comment by schifferl** [comment]
_From @edoardopasolli on December 6, 2017 15:37_

Thanks for catching this typo. I see that a similar problem is also affecting the KarlssonFH_2013 and the YuJ_2015 datasets.

@paolinomanghi could you generate the right NCBI_accession for these three datasets?

**Comment by schifferl** [comment]
_From @fplaza on December 6, 2017 15:57_

@schifferl 
Yes, all the HMP samples are concerned.

**Comment by edoardopasolli** [comment]
The issue has been fixed
