### ISSUE TITLE
adding curator

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#17]
_From @edoardopasolli on December 7, 2017 10:19_

since we are going to rebuild the package by fixing a few bugs in the metadata (as reported in another open issue), should we added the "curator" field? if yes, how we name it? and whick kind of information do we want to put (such as first+last name, email, etc.)?

_Copied from original issue: waldronlab/curatedMetagenomicData#117_

**Comment by edoardopasolli** [comment]
"curator" has been added in the template and in the metadata files
