### ISSUE TITLE
putative error in metadata for QinJ_2012

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#19]
_From @karchern on October 18, 2017 9:52_

Hi Guys,

In the metadata for QinJ_2012, the subject "CON-103" is listed 5 times (with different sample IDs, of course). I believe this is an error, as to my knowledge the study did not have any sort of time series / mutliple sampling.

Cheers!

_Copied from original issue: waldronlab/curatedMetagenomicData#107_

**Comment by schifferl** [comment]
Thanks, nick! Edo and I will look into it and provide corrected metadata.

**Comment by schifferl** [comment]
_From @paolinomanghi on December 6, 2017 15:56_

Ok, sto operando

**Comment by edoardopasolli** [comment]
The issue has been solved
