### ISSUE TITLE
Add publication title to `combined_metadata`

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#22]
_From @lwaldron on June 2, 2018 21:40_

Not sure exactly where I should create this issue, but will it be an easy addition to make some essential study information from PubMed (in particular, title) available in `combined_metadata` to be use in a mouse-over in the Shiny app? I see titles are in the help pages and experimentData of the ExpressionSet, but are they anywhere else accessible from within the package?

_Copied from original issue: waldronlab/curatedMetagenomicDataWorkflow#1_

**Comment by schifferl** [comment]
Easily done. I think this issue best fits in the curation repo, moving it there.

**Comment by lwaldron** [comment]
Can be looked up from PMID, so closing.
