### ISSUE TITLE
BMI in WenC_2017_metadata.tsv

### ISSUE THREAD

**Issue by kevinVervier** [waldronlab/curatedMetagenomicDataCuration#29]
Hi,
First of all, thank you for the amazing curation job you are doing here!
I found the BMI column in WenC_2017_metadata.tsv might have an issue with very high values (probably some decimal missing).
Cheers,
Kevin Vervier

**Comment by MarisaIsabell** [comment]
Hi. 
thank you for reporting this issue! 
I changed the BMI to the correct values by considering the original metadata from the study. 

best regards
Marisa Metzger

**Comment by lwaldron** [comment]
@cmirzayi will you make sure to take this corrected version in your next re-build of the package?
