### ISSUE TITLE
HMP2012: posterior fornix samples are incorrectly tagged as oral cavity

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#30]
_From @fplaza on February 11, 2019 8:25_

Hello,
posterior_fornix samples in the HMP_2012 are incorrectly tagged as 'oralcavity' whereas they should be as 'vagina'.
Could you fix this?

_Copied from original issue: waldronlab/curatedMetagenomicData#153_

**Comment by schifferl** [comment]
_From @edoardopasolli on February 11, 2019 8:34_

Thanks! Yes we were aware of this. It will be fixed in the next release.

**Comment by lwaldron** [comment]
This curation error was fixed in 696ba151ac32fade02991e9a90cd4adaa6ecb200 and no longer exists in dataset names, `pData`, or man pages, just in `combined_metadata`. So I'll close the issue here and leave it open at https://github.com/waldronlab/curatedMetagenomicData/issues/153
