### ISSUE TITLE
References updated in next update?

### ISSUE THREAD

**Issue by morganx** [waldronlab/curatedMetagenomicDataCuration#31]
References for Thomas AM 2018a & 2018b are currently missing from the reference manual. I presume one of them is PMID 30936548 & you're probably planning to include in next update but reminder not to forget :) Thanks.

**Comment by lwaldron** [comment]
Any chance you can still get this into the Bioc 3.10 release @schifferl?

**Comment by lwaldron** [comment]
pinging about this @schifferl - let me know if you need help with the maintenance.

**Comment by schifferl** [comment]
Hi @lwaldron, I can get to this tomorrow – I will send you an update and close the issue when it's done.

**Comment by schifferl** [comment]
Hello again, I haven't got this one done quite yet and can't seem to find the other PMID quickly. When you have a chance, could you add these @paolinomanghi? Then I will get this updated quickly in the devel branch of Bioconductor.

**Comment by lwaldron** [comment]
This was closed via 92e6f69
