### ISSUE TITLE
Typo in Heitz-BuschartA_2016

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#32]
There is a typo in the dataset name of "Heitz-BuschartA_2016", which should be "Heintz-BuschartA_2016"

**Comment by lwaldron** [comment]
This is an annoying error - since it's already been released, the wrong dataset name should go through the deprecation process. @schifferl are you up for it?

**Comment by schifferl** [comment]
I will take a look tomorrow and see what I can do to fix the problem (i.e. start the deprecation process).

**Comment by schifferl** [comment]
This requires an entire reprocessing of the data set, I've added this on Trello and will have it added to the devel branch of Bioconductor shortly.

**Comment by lwaldron** [comment]
I don't think we have anyone with the bandwidth to do this, so I think this name will have to be considered a feature rather than a bug. @schifferl please open again if you think you can handle as part of the release of cMD3.
