### ISSUE TITLE
A tiny little curation typo

### ISSUE THREAD

**Issue by morganx** [waldronlab/curatedMetagenomicDataCuration#33]
The field "study_condition" for Vatanen2016 contains both "pyelonefritis" (2 samples) and "pyelonephritis" (6 samples). You probably meant "pyelonephritis" for both?

**Comment by schifferl** [comment]
I've moved this issue to the curation repo, where it was closed by 7474b2b901851ffbfa01613b92ca525b4f46f006. It won't make the next release because that requires reprocessing the data set but will be rectified in the Bioconductor devel branch shortly.
