### ISSUE TITLE
Create a function that returns merged metadata

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataCuration#36]
1. When the package is installed, curation .tsv files will be listable using (this is approximate):
```r
filepaths <- list.files(system.file("inst/curation", package = "curatedMetagenomicDataCuration"), recursive = TRUE, pattern = "tsv$", full.names = TRUE)
```
Use this to create a vector of the paths to all curation tsv files.

2. read all of these using lapply and read.table or a function from the readr package, to create a list of data.frames. Test the read command using a single tsv file.
```r
dflist <- lapply(filepaths, function(x) read.table(x))`
```

3. Use [curatedMetagenomicData::joinListofDFs](https://github.com/waldronlab/curatedMetagenomicData/blob/e5fbf65509262a1a56471ec5767fa634b99c5117/R/mergeData.R#L80) to join the list of data.frames into a single big data.frame to return.

4. Add function to the R directory.
5. Add roxygen2 markup and use RStudio "Document package" to add a man page automatically.

**Comment by cmirzayi** [comment]
Added with https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/751b0aaae0aec664e6529df8503ba0691b5d6092
