### ISSUE TITLE
Additional metadata for Arumugam/Yu 2015, Hannigan 2018

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataCuration#42]
From: Muhammad Alsayid <Muhammad_Alsayid@rush.edu>
Date: Thursday, March 11, 2021 at 4:58 PM
To: Levi Waldron <Levi.Waldron@sph.cuny.edu>
Cc: Shirin Moossavi <shirin.moossavi@ucalgary.ca>
Subject: Re: Curated Metagenomic Data question

Dear Dr. Waldron,

I contacted the authors of 3 studies and 2 of them provided me with the metadata of their studies including age.

I attached the files I received from Dr. Arumugam regarding the study titled “Metagenomic analysis of faecal microbiome as a tool towards targeted non-invasive biomarkers for colorectal cancer” published in 2015 by Jun Yu et al.

I also got this link from Dr. Schloss regarding the article titled “Diagnostic Potential and Interactive Dynamics of the Colorectal Cancer Virome” published in 2018 by Hannigan et al.

https://github.com/SchlossLab/Hannigan_CRCVirome_mBio_2018/blob/master/data/metadata/303030-metadata.tsv

I hope you are able to merge this data with the curated Metagenomic Data so it can benefit others in the future.

Thanks so much,

Muhammad

 [Chinese_CRC_cohort_II_information_and_table16.xlsx](https://github.com/waldronlab/curatedMetagenomicDataCuration/files/6129733/Chinese_CRC_cohort_II_information_and_table16.xlsx)
[Chinese_cohort_I_final_info_updated.xlsx](https://github.com/waldronlab/curatedMetagenomicDataCuration/files/6129735/Chinese_cohort_I_final_info_updated.xlsx)

**Comment by lwaldron** [comment]
From @paolinomanghi:

Hi Levi, 
these are quite good (even tough we already added several metadata to the cohorts they guy mention, they will be available in next release). However I didn't have LDL & HDL levels, which is pretty good.
I need to add them. 

I'm just concerned about the sample IDs which are not exactly the one we took from NCBI, so it might be difficult.
I'm also confused about what is this "2nd chinese cohort": we actually do have just 1 chinese cohort for CRC in cMD.

Thanks

**Comment by lwaldron** [comment]
I think these correspond to:
* https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/curated/YuJ_2015/YuJ_2015_metadata.tsv
* https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/curated/HanniganGD_2017/HanniganGD_2017_metadata.tsv

**Comment by paolinomanghi** [comment]
Dear Muhammad,
thank you for your valuable contribution. I added your precious metadata to the YuJ-2015 study. They were great. The idea behind this package is exactly to sort out many clinical data tables like the ones you prepared. I didn't add anything to the Hannigan 2017 study because the info you provided were already included in the plan for the next release, but thanks the same.

If you don't mind, I would like to include you (your name & surname) as a curator for these two tables, like it is my common practice in this cases. For now, I'll close the issue. 
Thank you again

Paolo
