### ISSUE TITLE
make sure get_metadata() supports all studies

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataCuration#43]
https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/d084b1e3e033ca201e5ccc27b7b8af20163357cc/R/get_metadata.R#L22

Benchmark against all the tsv files in the repo.

**Comment by cmirzayi** [comment]
Progress has been made on this front. I heavily revised `get_metadata` in edd8e61a5b1987cf3e7bf22ab1f663a3d9b80901.

I will benchmark against all tsvs and then close this issue.

**Comment by cmirzayi** [comment]
Tested and works on all studies current in the repo.
