### ISSUE TITLE
write data/combined_metadata.rda

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataCuration#44]
1. Use the [makeCombinedMetadata](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/751b0aaae0aec664e6529df8503ba0691b5d6092/R/makeCombinedMetadata.R#L5) now in this package
2. Call this function in the GitHub Action, use `save(compression_level="bzip2")` to write to data/combined_metadata.rda, and push back to this repo

**Comment by jwokaty** [comment]
@cmirzayi How should I call your function? I get the following when I try calling your function:

```
> combined_metadata <- curatedMetagenomicDataCuration:::makeCombinedMetadata()
Error in fetchTSVs() : could not find function "fetchTSVs"
```

Is there a way to call it such that it recognizes the '.' prefixed functions?

**Comment by cmirzayi** [comment]
Whoops @jwokaty it should be fixed now.

**Comment by lwaldron** [comment]
There should be no more action necessary here, see https://github.com/waldronlab/curatedMetagenomicData/issues/174. Will close for now. 

> Whoops @jwokaty it should be fixed now.

BTW @cmirzayi it's useful to reference the hash of the commit of the fix, to make it easier to see how you did it, e.g.: 18c504cdc1b331ecfa58776cc3e195512c8c251e
