### ISSUE TITLE
change PMID specifications

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#55]
The current PMID specification is almost right but the `unpublished` values creates a few issues for me in the R package, it would be better if these were just blank. The following changes to the template (and curated files) would be helpful.

requiredness:
optional

allowedvalues:
[0-9]{8}|unpublished -> [0-9]{8}

**Comment by paolinomanghi** [comment]
I have allowed NA instead of unpublished, and I have amended the two datasets for which the table said unpublished. I'm closing this
