### ISSUE TITLE
trailing decimal zero in a few variables

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#56]
There are values like `2.0` instead of just `2` in a number to the curated files for variables that are specified as integers by `col.class` which turn into parsing errors when I read them in with R in the cMD package. Here's a short list of the variables I've identified:

- `age`
- `infant_age`
- `days_from_first_collection`
- `median_read_length`
- `minimum_read_length`
- `days_after_onset`
- `number_reads`
- `ctp`
- `birth_order`
- `age_twins_started_to_live_apart`
- `breastfeeding_duration`

The trailing zero should be removed in the curated files, if it is not too difficult to do.

**Comment by paolinomanghi** [comment]
Closing this issue.

**Comment by schifferl** [comment]
I think maybe some changes weren't pushed (or something like that), but I fixed this with 274e795.
