### ISSUE TITLE
KarlssonFH_2013: Nothing has been found for accessions

### ISSUE THREAD

**Issue by qifei9** [waldronlab/curatedMetagenomicDataCuration#59]
In study `KarlssonFH_2013`, samples `S60` and `S602` have NCBI accessions `ERR260212` and `ERR260213` respectively. However, nothing can be found for these 2 accessions in NCBI.

**Comment by lwaldron** [comment]
Very sorry for the delay here - @paolinomanghi will you be able to resolve this for the Bioconductor 3.14 release?
