### ISSUE TITLE
QinN_2014: duplicate accession

### ISSUE THREAD

**Issue by qifei9** [waldronlab/curatedMetagenomicDataCuration#60]
In study `QinN_2014`, the sample `HD-1` has NCBI accession of `ERR528329;ERR528329;ERR526291` where the first 2 accessions are identical.

**Comment by lwaldron** [comment]
Very sorry for the delay here - @paolinomanghi will you be able to resolve this for the Bioconductor 3.14 release? This one is a very quick fix (although it isn't hurting anything).
