### ISSUE TITLE
remove sample_id MSM6J2HB from HMP_2019_ibdmdb

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#66]
In the `HMP_2019_ibdmdb` metadata file, `sample_id` **MSM6J2HB** should be removed – it is not in the matrix file that is on ExperimentHub and always makes the number of samples reported by the `sampleMetadata` table in curatedMetagenomicData wrong.

**Comment by paolinomanghi** [comment]
I fixed this. The table I used previously was already without this one but for some reason I did finish the commit. Done, sorry.
