### ISSUE TITLE
PehrssonE_2016 metadata file contains duplicate entries

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#67]
There is a duplicate `sample_id` (**SID03C_000**) in the `PehrssonE_2016` metadata file – the duplicate row should be removed.

**Comment by paolinomanghi** [comment]
Ok, I introduced this bug two weeks ago, now I solved it.

**Comment by schifferl** [comment]
Thanks @paolinomanghi
