### ISSUE TITLE
VincentC_2016 Antibiotics Metadata do not match published paper

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/curatedMetagenomicDataCuration#68]
`antibiotics_family` and `antibiotics_current_use` appear to be wrong for many of the samples for the VincentC_2016 study.

All 229 samples are coded as `yes` for `antibiotics_current_use` but that is not true according to the original paper. A handful of participants never received antibiotics over the course of the study and many did not begin the study on antibiotics.

Additionally there are issues with the classes of antibiotics. For instance, the [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4791782/) states that 81 samples in the control group alone were exposed to cephalosporins and yet the data in cMD seem to only have 5 samples with cephalosporins exposure:
```
                                                                                  study_name
antibiotics_family                                                                 VincentC_2016
  aminoglycosides;beta_lactamase_inhibitors;laxatives;penicillin                               1
  beta_lactamase_inhibitors;carbapenems;cephalosporins;fluoroquinolones;penicillin             2
  beta_lactamase_inhibitors;carbapenems;cephalosporins;penicillin                              1
  beta_lactamase_inhibitors;carbapenems;fluoroquinolones;penicillin                            2
  beta_lactamase_inhibitors;macrolides;penicillin                                              2
  beta_lactamase_inhibitors;penicillin                                                         6
  carbapenems                                                                                  4
  carbapenems;fluoroquinolones                                                                 7
  carbapenems;fluoroquinolones;laxatives                                                       1
  carbapenems;laxatives                                                                        1
  cephalosporins                                                                               2
  fluoroquinolones                                                                             2
  macrolides                                                                                   2
```

The culprit here seems to be the incomplete [ metadata available on SRA](http://www.ncbi.nlm.nih.gov/sra/SRP064400), but the numbers on SRA also don't seem to quite match what's in cMD either--the SRA data for instance list 4 unique samples with cephalosporins exposure.

Where did the data for `antibiotics_family` come from?

I've already emailed the corresponding author of the original paper to see if she can provide some clarifications/a more comprehensive metadata table but haven't heard anything back yet. However, it would be helpful to have someone more familiar with the curation of these data look into this as well.

**Comment by cmirzayi** [comment]
I have heard back from the corresponding author and the corrected metadata and accompanying data dictionary are attached.
[data_dictionary_09062022.xlsx](https://github.com/waldronlab/curatedMetagenomicDataCuration/files/9834260/data_dictionary_09062022.xlsx)
[jgh_09062022.csv](https://github.com/waldronlab/curatedMetagenomicDataCuration/files/9834261/jgh_09062022.csv)

**Comment by paolinomanghi** [comment]
Thanks @Chloe Mirzayi ***@***.***> , this is great! I will
add it asap!

**Comment by AndreaZen-1** [comment]
This is solved, I'm closing.
