### ISSUE TITLE
"LiJ_2014" dataset

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#8]
It seems that the "LiJ_2014" overlaps in some way with three other datasets: "LeChatelierE_2013", "NielsenHB_2014", "QinJ_2012".
More curation of the fields "sampleID" and "subjectID" is necessary

**Comment by lwaldron** [comment]
We will start a duplicates table, rather than changing sampleID and subjectID identifiers.

**Comment by lwaldron** [comment]
Duplicate of #14
